from __future__ import annotations

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.models import Dish
from app.services.nutrition import evaluate_nutrition

SAMPLE_DISHES = [
    {
        "name": "Avena con platano y canela",
        "meal_type": "desayuno",
        "ingredients": "avena, leche, platano, canela, miel",
        "cost_per_serving": 3.2,
        "calories": 380,
        "protein_g": 12,
        "carbs_g": 64,
        "fat_g": 8,
        "fiber_g": 7,
        "sugar_g": 14,
        "sodium_mg": 120,
    },
    {
        "name": "Pan integral con huevo y palta",
        "meal_type": "desayuno",
        "ingredients": "pan integral, huevo, palta, tomate",
        "cost_per_serving": 4.1,
        "calories": 420,
        "protein_g": 17,
        "carbs_g": 36,
        "fat_g": 22,
        "fiber_g": 6,
        "sugar_g": 5,
        "sodium_mg": 310,
    },
    {
        "name": "Yogurt natural con fruta y granola",
        "meal_type": "desayuno",
        "ingredients": "yogurt natural, fresa, platano, granola",
        "cost_per_serving": 4.5,
        "calories": 350,
        "protein_g": 13,
        "carbs_g": 47,
        "fat_g": 11,
        "fiber_g": 5,
        "sugar_g": 16,
        "sodium_mg": 160,
    },
    {
        "name": "Quinua cocida con leche y manzana",
        "meal_type": "desayuno",
        "ingredients": "quinua, leche, manzana, canela",
        "cost_per_serving": 3.8,
        "calories": 390,
        "protein_g": 14,
        "carbs_g": 60,
        "fat_g": 9,
        "fiber_g": 6,
        "sugar_g": 12,
        "sodium_mg": 130,
    },
    {
        "name": "Tortilla de verduras",
        "meal_type": "desayuno",
        "ingredients": "huevo, espinaca, tomate, cebolla",
        "cost_per_serving": 4.0,
        "calories": 330,
        "protein_g": 18,
        "carbs_g": 14,
        "fat_g": 20,
        "fiber_g": 4,
        "sugar_g": 4,
        "sodium_mg": 290,
    },
    {
        "name": "Sandwich integral de pollo",
        "meal_type": "desayuno",
        "ingredients": "pan integral, pollo deshilachado, lechuga, tomate",
        "cost_per_serving": 4.9,
        "calories": 410,
        "protein_g": 24,
        "carbs_g": 40,
        "fat_g": 12,
        "fiber_g": 5,
        "sugar_g": 6,
        "sodium_mg": 380,
    },
    {
        "name": "Tamal de pollo casero ligero",
        "meal_type": "desayuno",
        "ingredients": "masa de maiz, pollo, aji panca, cebolla",
        "cost_per_serving": 5.5,
        "calories": 520,
        "protein_g": 20,
        "carbs_g": 62,
        "fat_g": 20,
        "fiber_g": 4,
        "sugar_g": 4,
        "sodium_mg": 620,
    },
    {
        "name": "Panqueques integrales de avena",
        "meal_type": "desayuno",
        "ingredients": "avena, huevo, leche, platano",
        "cost_per_serving": 4.2,
        "calories": 400,
        "protein_g": 15,
        "carbs_g": 55,
        "fat_g": 12,
        "fiber_g": 6,
        "sugar_g": 12,
        "sodium_mg": 220,
    },
    {
        "name": "Lentejas con arroz y ensalada",
        "meal_type": "almuerzo",
        "ingredients": "lentejas, arroz, zanahoria, tomate, cebolla",
        "cost_per_serving": 6.8,
        "calories": 620,
        "protein_g": 24,
        "carbs_g": 92,
        "fat_g": 14,
        "fiber_g": 12,
        "sugar_g": 7,
        "sodium_mg": 520,
    },
    {
        "name": "Pollo guisado con papa y ensalada",
        "meal_type": "almuerzo",
        "ingredients": "pollo, papa, zanahoria, cebolla, tomate",
        "cost_per_serving": 7.5,
        "calories": 670,
        "protein_g": 32,
        "carbs_g": 64,
        "fat_g": 24,
        "fiber_g": 8,
        "sugar_g": 8,
        "sodium_mg": 670,
    },
    {
        "name": "Pescado al horno con camote",
        "meal_type": "almuerzo",
        "ingredients": "pescado, camote, limon, ensalada",
        "cost_per_serving": 8.7,
        "calories": 580,
        "protein_g": 35,
        "carbs_g": 56,
        "fat_g": 18,
        "fiber_g": 7,
        "sugar_g": 9,
        "sodium_mg": 450,
    },
    {
        "name": "Quinua chaufa con verduras",
        "meal_type": "almuerzo",
        "ingredients": "quinua, huevo, pimiento, cebolla china, pollo",
        "cost_per_serving": 7.1,
        "calories": 640,
        "protein_g": 28,
        "carbs_g": 74,
        "fat_g": 21,
        "fiber_g": 9,
        "sugar_g": 8,
        "sodium_mg": 720,
    },
    {
        "name": "Tallarin integral con atun",
        "meal_type": "almuerzo",
        "ingredients": "tallarin integral, atun, tomate, cebolla",
        "cost_per_serving": 7.9,
        "calories": 690,
        "protein_g": 33,
        "carbs_g": 78,
        "fat_g": 24,
        "fiber_g": 8,
        "sugar_g": 10,
        "sodium_mg": 760,
    },
    {
        "name": "Estofado de carne magra",
        "meal_type": "almuerzo",
        "ingredients": "carne magra, papa, zanahoria, arvejas",
        "cost_per_serving": 8.3,
        "calories": 700,
        "protein_g": 34,
        "carbs_g": 66,
        "fat_g": 26,
        "fiber_g": 7,
        "sugar_g": 9,
        "sodium_mg": 710,
    },
    {
        "name": "Seco de pollo con frejoles",
        "meal_type": "almuerzo",
        "ingredients": "pollo, culantro, frejoles, arroz",
        "cost_per_serving": 7.7,
        "calories": 730,
        "protein_g": 31,
        "carbs_g": 82,
        "fat_g": 23,
        "fiber_g": 10,
        "sugar_g": 6,
        "sodium_mg": 780,
    },
    {
        "name": "Sopa de verduras con pollo y fideos",
        "meal_type": "almuerzo",
        "ingredients": "pollo, fideos, zanahoria, apio, papa",
        "cost_per_serving": 6.9,
        "calories": 560,
        "protein_g": 27,
        "carbs_g": 62,
        "fat_g": 15,
        "fiber_g": 6,
        "sugar_g": 7,
        "sodium_mg": 610,
    },
    {
        "name": "Crema de verduras con tostadas",
        "meal_type": "cena",
        "ingredients": "zapallo, zanahoria, papa, pan integral",
        "cost_per_serving": 4.7,
        "calories": 340,
        "protein_g": 10,
        "carbs_g": 52,
        "fat_g": 9,
        "fiber_g": 6,
        "sugar_g": 9,
        "sodium_mg": 280,
    },
    {
        "name": "Tortilla de atun y espinaca",
        "meal_type": "cena",
        "ingredients": "atun, huevo, espinaca, cebolla",
        "cost_per_serving": 5.4,
        "calories": 390,
        "protein_g": 29,
        "carbs_g": 8,
        "fat_g": 24,
        "fiber_g": 3,
        "sugar_g": 2,
        "sodium_mg": 650,
    },
    {
        "name": "Ensalada de garbanzos",
        "meal_type": "cena",
        "ingredients": "garbanzo, pepino, tomate, aceite de oliva",
        "cost_per_serving": 4.9,
        "calories": 360,
        "protein_g": 14,
        "carbs_g": 43,
        "fat_g": 14,
        "fiber_g": 9,
        "sugar_g": 7,
        "sodium_mg": 300,
    },
    {
        "name": "Arroz integral con pollo deshilachado",
        "meal_type": "cena",
        "ingredients": "arroz integral, pollo, pimiento, cebolla",
        "cost_per_serving": 5.8,
        "calories": 470,
        "protein_g": 27,
        "carbs_g": 48,
        "fat_g": 16,
        "fiber_g": 5,
        "sugar_g": 5,
        "sodium_mg": 470,
    },
    {
        "name": "Pure de zapallo con huevo sancochado",
        "meal_type": "cena",
        "ingredients": "zapallo, papa, huevo, leche",
        "cost_per_serving": 4.3,
        "calories": 380,
        "protein_g": 13,
        "carbs_g": 46,
        "fat_g": 14,
        "fiber_g": 5,
        "sugar_g": 8,
        "sodium_mg": 320,
    },
    {
        "name": "Salteado de verduras y pavo",
        "meal_type": "cena",
        "ingredients": "pavo, brocoli, zanahoria, pimiento",
        "cost_per_serving": 6.2,
        "calories": 420,
        "protein_g": 31,
        "carbs_g": 22,
        "fat_g": 18,
        "fiber_g": 6,
        "sugar_g": 8,
        "sodium_mg": 480,
    },
    {
        "name": "Sopa de quinua y pollo",
        "meal_type": "cena",
        "ingredients": "quinua, pollo, zanahoria, apio",
        "cost_per_serving": 5.1,
        "calories": 410,
        "protein_g": 25,
        "carbs_g": 42,
        "fat_g": 14,
        "fiber_g": 6,
        "sugar_g": 6,
        "sodium_mg": 410,
    },
    {
        "name": "Ceviche de garbanzos",
        "meal_type": "cena",
        "ingredients": "garbanzo, limon, cebolla morada, culantro",
        "cost_per_serving": 4.6,
        "calories": 330,
        "protein_g": 13,
        "carbs_g": 39,
        "fat_g": 11,
        "fiber_g": 8,
        "sugar_g": 6,
        "sodium_mg": 290,
    },
    {
        "name": "Rollitos de pavo y queso",
        "meal_type": "lonchera",
        "ingredients": "jamon de pavo, queso fresco, pepino",
        "cost_per_serving": 3.4,
        "calories": 210,
        "protein_g": 16,
        "carbs_g": 6,
        "fat_g": 14,
        "fiber_g": 1,
        "sugar_g": 3,
        "sodium_mg": 540,
    },
    {
        "name": "Fruta picada con nueces",
        "meal_type": "lonchera",
        "ingredients": "manzana, platano, nueces",
        "cost_per_serving": 2.9,
        "calories": 240,
        "protein_g": 5,
        "carbs_g": 30,
        "fat_g": 12,
        "fiber_g": 5,
        "sugar_g": 17,
        "sodium_mg": 40,
    },
    {
        "name": "Sandwich integral de huevo",
        "meal_type": "lonchera",
        "ingredients": "pan integral, huevo, tomate, lechuga",
        "cost_per_serving": 3.7,
        "calories": 310,
        "protein_g": 14,
        "carbs_g": 32,
        "fat_g": 14,
        "fiber_g": 4,
        "sugar_g": 5,
        "sodium_mg": 330,
    },
    {
        "name": "Yogurt natural con avena",
        "meal_type": "lonchera",
        "ingredients": "yogurt natural, avena, miel",
        "cost_per_serving": 3.1,
        "calories": 260,
        "protein_g": 11,
        "carbs_g": 34,
        "fat_g": 8,
        "fiber_g": 4,
        "sugar_g": 13,
        "sodium_mg": 120,
    },
    {
        "name": "Muffin casero de platano",
        "meal_type": "lonchera",
        "ingredients": "platano, harina integral, huevo, avena",
        "cost_per_serving": 3.5,
        "calories": 290,
        "protein_g": 7,
        "carbs_g": 42,
        "fat_g": 10,
        "fiber_g": 4,
        "sugar_g": 15,
        "sodium_mg": 190,
    },
    {
        "name": "Mini wraps de pollo",
        "meal_type": "lonchera",
        "ingredients": "tortilla integral, pollo, lechuga, zanahoria",
        "cost_per_serving": 4.2,
        "calories": 300,
        "protein_g": 18,
        "carbs_g": 30,
        "fat_g": 12,
        "fiber_g": 4,
        "sugar_g": 4,
        "sodium_mg": 360,
    },
    {
        "name": "Palitos de zanahoria con hummus",
        "meal_type": "lonchera",
        "ingredients": "zanahoria, garbanzo, limon, aceite de oliva",
        "cost_per_serving": 2.8,
        "calories": 220,
        "protein_g": 8,
        "carbs_g": 24,
        "fat_g": 10,
        "fiber_g": 6,
        "sugar_g": 6,
        "sodium_mg": 170,
    },
    {
        "name": "Galletas de avena y leche",
        "meal_type": "lonchera",
        "ingredients": "avena, harina integral, leche, pasas",
        "cost_per_serving": 3.0,
        "calories": 280,
        "protein_g": 8,
        "carbs_g": 38,
        "fat_g": 10,
        "fiber_g": 4,
        "sugar_g": 14,
        "sodium_mg": 180,
    },
    {
        "name": "Emoliente casero",
        "meal_type": "refresco",
        "ingredients": "cebada, linaza, limon, canela",
        "cost_per_serving": 1.3,
        "calories": 80,
        "protein_g": 2,
        "carbs_g": 17,
        "fat_g": 1,
        "fiber_g": 2,
        "sugar_g": 4,
        "sodium_mg": 20,
    },
    {
        "name": "Limonada sin azucar",
        "meal_type": "refresco",
        "ingredients": "limon, agua, stevia",
        "cost_per_serving": 0.9,
        "calories": 35,
        "protein_g": 0,
        "carbs_g": 8,
        "fat_g": 0,
        "fiber_g": 1,
        "sugar_g": 2,
        "sodium_mg": 5,
    },
    {
        "name": "Agua de avena y canela",
        "meal_type": "refresco",
        "ingredients": "avena, canela, agua",
        "cost_per_serving": 1.2,
        "calories": 70,
        "protein_g": 2,
        "carbs_g": 15,
        "fat_g": 1,
        "fiber_g": 1,
        "sugar_g": 3,
        "sodium_mg": 10,
    },
    {
        "name": "Chicha morada baja en azucar",
        "meal_type": "refresco",
        "ingredients": "maiz morado, pina, canela, clavo",
        "cost_per_serving": 1.8,
        "calories": 95,
        "protein_g": 1,
        "carbs_g": 22,
        "fat_g": 0,
        "fiber_g": 1,
        "sugar_g": 8,
        "sodium_mg": 12,
    },
    {
        "name": "Infusion de hierba luisa",
        "meal_type": "refresco",
        "ingredients": "hierba luisa, agua, limon",
        "cost_per_serving": 0.8,
        "calories": 15,
        "protein_g": 0,
        "carbs_g": 3,
        "fat_g": 0,
        "fiber_g": 0,
        "sugar_g": 0,
        "sodium_mg": 3,
    },
    {
        "name": "Jugo de maracuya diluido",
        "meal_type": "refresco",
        "ingredients": "maracuya, agua, stevia",
        "cost_per_serving": 1.6,
        "calories": 60,
        "protein_g": 1,
        "carbs_g": 14,
        "fat_g": 0,
        "fiber_g": 1,
        "sugar_g": 7,
        "sodium_mg": 7,
    },
    {
        "name": "Refresco de manzana y canela",
        "meal_type": "refresco",
        "ingredients": "manzana, canela, agua",
        "cost_per_serving": 1.4,
        "calories": 55,
        "protein_g": 0,
        "carbs_g": 13,
        "fat_g": 0,
        "fiber_g": 1,
        "sugar_g": 8,
        "sodium_mg": 6,
    },
    {
        "name": "Agua saborizada con frutas",
        "meal_type": "refresco",
        "ingredients": "fresa, pepino, limon, agua",
        "cost_per_serving": 1.1,
        "calories": 30,
        "protein_g": 0,
        "carbs_g": 7,
        "fat_g": 0,
        "fiber_g": 1,
        "sugar_g": 3,
        "sodium_mg": 4,
    },
]


MEAL_MACRO_PROFILE = {
    "desayuno": {"protein_pct": 0.18, "carb_pct": 0.50, "fat_pct": 0.32, "fiber_g": 5.5, "sugar_g": 11.0, "sodium_mg": 280.0, "sodium_per_cal": 0.9},
    "almuerzo": {"protein_pct": 0.22, "carb_pct": 0.45, "fat_pct": 0.33, "fiber_g": 8.0, "sugar_g": 8.0, "sodium_mg": 520.0, "sodium_per_cal": 1.05},
    "cena": {"protein_pct": 0.24, "carb_pct": 0.38, "fat_pct": 0.38, "fiber_g": 6.0, "sugar_g": 6.0, "sodium_mg": 430.0, "sodium_per_cal": 0.8},
    "lonchera": {"protein_pct": 0.16, "carb_pct": 0.50, "fat_pct": 0.34, "fiber_g": 4.0, "sugar_g": 12.0, "sodium_mg": 230.0, "sodium_per_cal": 0.45},
    "refresco": {"protein_pct": 0.05, "carb_pct": 0.92, "fat_pct": 0.03, "fiber_g": 1.0, "sugar_g": 7.0, "sodium_mg": 18.0, "sodium_per_cal": 0.08},
}


EXTRA_PERUVIAN_SPECS: list[tuple[str, str, str, float, int]] = [
    ("desayuno", "Pan con chicharron limeno", "pan frances, chicharron, camote, salsa criolla", 6.2, 590),
    ("desayuno", "Tamal verde de pollo", "maiz molido, culantro, pollo, aji verde", 5.8, 540),
    ("desayuno", "Humita dulce casera", "choclo, queso fresco, anis, azucar rubia", 4.6, 430),
    ("desayuno", "Quinua atamalada con manzana", "quinua, leche, manzana, canela", 4.4, 410),
    ("desayuno", "Sanguche de pavo criollo", "pan integral, pavo, cebolla, tomate", 5.1, 460),
    ("desayuno", "Pan con tortilla de atun", "pan integral, atun, huevo, lechuga", 4.8, 440),
    ("desayuno", "Ensalada de frutas con kiwicha", "papaya, platano, manzana, kiwicha", 4.3, 390),
    ("desayuno", "Torrejas de acelga con queso fresco", "acelga, huevo, queso fresco, harina", 4.7, 420),
    ("desayuno", "Pan con palta y aceituna", "pan integral, palta, aceituna, tomate", 4.2, 370),
    ("desayuno", "Cachanga integral con miel", "harina integral, anis, miel, huevo", 4.5, 450),
    ("desayuno", "Pan con asado y salsa criolla", "pan frances, asado de res, cebolla, limon", 6.4, 610),
    ("desayuno", "Api morado con pan integral", "maiz morado, canela, clavo, pan integral", 3.9, 380),
    ("desayuno", "Tortilla de choclo con queso", "choclo, huevo, queso fresco, cebolla", 4.8, 460),
    ("desayuno", "Omelette andino de quinua", "huevo, quinua cocida, espinaca, tomate", 4.6, 430),
    ("desayuno", "Sandwich de pejerrey a la plancha", "pan integral, pejerrey, lechuga, limon", 5.4, 500),
    ("desayuno", "Mazamorra de avena y manzana", "avena, manzana, canela, leche", 4.1, 360),
    ("desayuno", "Panqueques de kiwicha y platano", "kiwicha, platano, huevo, leche", 4.7, 440),
    ("desayuno", "Pan con huevo revuelto y aji amarillo", "pan integral, huevo, aji amarillo, cebolla", 4.3, 410),
    ("desayuno", "Tostadas andinas con queso y tomate", "pan andino, queso fresco, tomate, oregano", 4.0, 350),
    ("desayuno", "Batido de quinua con cacao y leche", "quinua, cacao, leche, platano", 4.9, 420),
    ("almuerzo", "Aji de gallina ligero", "pollo, leche, nuez, aji amarillo, arroz", 9.8, 780),
    ("almuerzo", "Lomo saltado casero", "res, cebolla, tomate, sillao, papa", 10.5, 820),
    ("almuerzo", "Arroz con pollo a la peruana", "pollo, arroz, culantro, arvejas, zanahoria", 9.1, 760),
    ("almuerzo", "Seco de res con frejoles", "res, culantro, frejoles, arroz, cebolla", 10.2, 810),
    ("almuerzo", "Tacu tacu con bistec", "frejol canario, arroz, bistec, huevo", 9.7, 790),
    ("almuerzo", "Causa rellena de atun", "papa amarilla, atun, palta, limon", 8.6, 650),
    ("almuerzo", "Papa a la huancaina con filete de pollo", "papa, queso fresco, aji amarillo, pollo", 8.9, 700),
    ("almuerzo", "Carapulcra con sopa seca", "papa seca, cerdo, mani, tallarin", 10.8, 830),
    ("almuerzo", "Chaufa de quinua con pollo", "quinua, pollo, huevo, cebolla china", 9.4, 740),
    ("almuerzo", "Sudado de pescado con yuca", "pescado, tomate, cebolla, yuca, culantro", 10.1, 720),
    ("almuerzo", "Escabeche de pollo casero", "pollo, cebolla roja, vinagre, camote", 8.8, 690),
    ("almuerzo", "Arroz tapado de carne", "arroz, carne molida, pasas, huevo", 9.6, 760),
    ("almuerzo", "Cau cau de mondongo ligero", "mondongo, papa, hierbabuena, aji amarillo", 9.2, 680),
    ("almuerzo", "Pallares guisados con arroz", "pallares, arroz, cebolla, tomate", 8.4, 640),
    ("almuerzo", "Chupe de quinua con verduras", "quinua, leche, zapallo, zanahoria, papa", 8.9, 620),
    ("almuerzo", "Arroz con mariscos casero", "arroz, mariscos, aji panca, culantro", 11.2, 840),
    ("almuerzo", "Olluquito con carne", "olluco, carne de res, perejil, cebolla", 9.5, 700),
    ("almuerzo", "Adobo arequipeno de cerdo", "cerdo, chicha de jora, ajo, aji panca", 10.9, 850),
    ("almuerzo", "Menestron peruano con pollo", "fideos, verduras, pollo, albahaca", 9.0, 690),
    ("almuerzo", "Picante de pollo con papa", "pollo, papa, aji panca, mani", 9.3, 730),
    ("cena", "Sopa criolla ligera", "fideos, leche, huevo, oregano, tomate", 7.2, 520),
    ("cena", "Caldo de gallina casero", "gallina, fideos, huevo, cebolla china", 8.1, 610),
    ("cena", "Causa de pollo light", "papa amarilla, pollo, yogurt, limon", 6.8, 480),
    ("cena", "Ensalada de quinua y anchoveta", "quinua, anchoveta, tomate, pepino", 7.0, 430),
    ("cena", "Pescado a la chorrillana", "pescado, cebolla, tomate, aji amarillo", 8.4, 560),
    ("cena", "Tortilla de vainitas y papa", "vainitas, papa, huevo, queso fresco", 6.5, 470),
    ("cena", "Saltado de verduras con tofu criollo", "tofu, pimiento, cebolla, salsa de soya", 7.4, 450),
    ("cena", "Ajiaco de papa con huevo", "papa, leche, aji amarillo, huevo", 6.9, 490),
    ("cena", "Sopa de mote con verduras", "mote, zanahoria, apio, papa", 6.2, 410),
    ("cena", "Crema de choclo y queso fresco", "choclo, leche, queso fresco, cebolla", 6.7, 440),
    ("cena", "Pollo al horno con ensalada rusa ligera", "pollo, papa, zanahoria, arvejas", 8.2, 580),
    ("cena", "Atun encebollado con camote", "atun, cebolla roja, camote, limon", 6.8, 460),
    ("cena", "Ensalada de pallares con tomate", "pallares, tomate, cebolla, perejil", 6.1, 420),
    ("cena", "Pastel de papa con carne magra", "papa, carne magra, leche, huevo", 7.3, 530),
    ("cena", "Sancochado de res ligero", "res, yuca, papa, col, apio", 8.9, 650),
    ("cena", "Locro de zapallo con queso", "zapallo, papa, queso fresco, leche", 6.6, 470),
    ("cena", "Sopa de fideos con huevo", "fideos, huevo, apio, zanahoria", 5.9, 390),
    ("cena", "Revuelto de zapallito y pavo", "zapallito, pavo, cebolla, tomate", 7.1, 440),
    ("cena", "Ensalada de tarwi y palta", "tarwi, palta, tomate, limon", 6.4, 430),
    ("cena", "Brochetas de pollo anticuchero", "pollo, aji panca, comino, pimiento", 7.8, 520),
    ("lonchera", "Triple de pollo y palta", "pan molde integral, pollo, palta, tomate", 4.8, 340),
    ("lonchera", "Alfajor de avena casero", "avena, harina integral, manjar ligero", 3.5, 290),
    ("lonchera", "Bolitas de kiwicha y datil", "kiwicha, datil, mani, miel", 3.1, 230),
    ("lonchera", "Queque de zanahoria integral", "zanahoria, harina integral, huevo, canela", 3.4, 270),
    ("lonchera", "Brochetas de fruta con yogurt", "fresa, uva, platano, yogurt", 3.2, 240),
    ("lonchera", "Pan con tortilla de verduras", "pan integral, huevo, espinaca, tomate", 3.8, 300),
    ("lonchera", "Mini causa de atun", "papa amarilla, atun, limon, zanahoria", 3.9, 280),
    ("lonchera", "Cancha serrana con queso fresco", "maiz cancha, queso fresco, sal", 2.9, 210),
    ("lonchera", "Palitos de pepino y zanahoria con dip de palta", "pepino, zanahoria, palta, yogurt", 3.0, 190),
    ("lonchera", "Pan de yuca casero", "harina de yuca, queso, huevo, leche", 3.6, 260),
    ("lonchera", "Ensalada de frutas con granadilla", "papaya, granadilla, manzana, uva", 3.3, 250),
    ("lonchera", "Pan pita con hummus de pallares", "pan pita integral, pallares, limon, ajo", 3.4, 270),
    ("lonchera", "Mini empanada de pollo al horno", "harina integral, pollo, cebolla, huevo", 3.7, 300),
    ("lonchera", "Queso fresco con membrillo y galleta integral", "queso fresco, membrillo, galleta integral", 3.2, 230),
    ("lonchera", "Roll de quinua y verduras", "quinua, zanahoria, pepino, palta", 3.5, 260),
    ("lonchera", "Mini pan con pechuga deshilachada", "pan mini, pechuga de pollo, lechuga", 3.8, 290),
    ("lonchera", "Gelatina de frutas sin azucar", "gelatina sin azucar, fresa, manzana", 2.7, 180),
    ("lonchera", "Chips de camote al horno", "camote, aceite de oliva, sal", 2.9, 200),
    ("lonchera", "Barrita de kiwicha y mani", "kiwicha, mani, miel, cacao", 3.1, 240),
    ("lonchera", "Yogurt bebible de fresa casero", "yogurt, fresa, avena, stevia", 3.0, 220),
    ("refresco", "Chicha de quinua", "quinua, canela, limon, agua", 1.7, 85),
    ("refresco", "Agua de cebada tostada", "cebada tostada, limon, agua", 1.2, 50),
    ("refresco", "Refresco de cocona", "cocona, agua, stevia", 1.8, 70),
    ("refresco", "Jugo de camu camu diluido", "camu camu, agua, stevia", 2.0, 65),
    ("refresco", "Agua de pina con hierbabuena", "pina, hierbabuena, agua", 1.5, 45),
    ("refresco", "Maracuya con mango diluido", "maracuya, mango, agua", 1.9, 80),
    ("refresco", "Limonada de hierbabuena", "limon, hierbabuena, stevia", 1.3, 35),
    ("refresco", "Jugo de papaya con naranja", "papaya, naranja, agua", 1.8, 75),
    ("refresco", "Refresco de pera con canela", "pera, canela, agua", 1.4, 55),
    ("refresco", "Infusion fria de muna", "muna, limon, agua", 1.1, 20),
    ("refresco", "Agua de linaza con limon", "linaza, limon, agua", 1.2, 30),
    ("refresco", "Refresco de tamarindo ligero", "tamarindo, agua, stevia", 1.6, 60),
    ("refresco", "Jugo de melocoton sin azucar", "melocoton, agua, stevia", 1.7, 65),
    ("refresco", "Mate de coca frio", "hoja de coca, limon, agua", 1.0, 25),
    ("refresco", "Agua de sandia con limon", "sandia, limon, agua", 1.4, 40),
    ("refresco", "Refresco frio de manzanilla", "manzanilla, limon, agua", 1.1, 18),
    ("refresco", "Jugo de aguaymanto diluido", "aguaymanto, agua, stevia", 1.9, 70),
    ("refresco", "Chicha de jora sin azucar", "chicha de jora, agua, limon", 1.5, 50),
    ("refresco", "Refresco de maiz morado con arandano", "maiz morado, arandano, canela, agua", 2.1, 90),
    ("refresco", "Agua de pepino con limon", "pepino, limon, agua", 1.2, 28),
]


def _build_dish_row_from_spec(spec: tuple[str, str, str, float, int]) -> dict:
    meal_type, name, ingredients, cost_per_serving, calories = spec
    profile = MEAL_MACRO_PROFILE[meal_type]

    protein_g = round((calories * profile["protein_pct"]) / 4, 1)
    carbs_g = round((calories * profile["carb_pct"]) / 4, 1)
    fat_g = round((calories * profile["fat_pct"]) / 9, 1)
    fiber_g = round(profile["fiber_g"] + max(0, (calories - 260) / 280), 1)
    sugar_g = round(profile["sugar_g"] + (calories / 600), 1)
    sodium_mg = round(profile["sodium_mg"] + max(0, calories - 180) * profile["sodium_per_cal"], 1)

    return {
        "name": name,
        "meal_type": meal_type,
        "ingredients": ingredients,
        "cost_per_serving": cost_per_serving,
        "calories": calories,
        "protein_g": protein_g,
        "carbs_g": carbs_g,
        "fat_g": fat_g,
        "fiber_g": fiber_g,
        "sugar_g": sugar_g,
        "sodium_mg": sodium_mg,
    }


EXTRA_PERUVIAN_DISHES = [_build_dish_row_from_spec(spec) for spec in EXTRA_PERUVIAN_SPECS]
ALL_SEED_DISHES = SAMPLE_DISHES + EXTRA_PERUVIAN_DISHES


def seed_default_dishes(session: Session) -> int:
    existing_names = set(session.scalars(select(Dish.name)).all())
    inserted = 0

    for row in ALL_SEED_DISHES:
        if row["name"] in existing_names:
            continue
        is_healthy, auto_benefits, auto_warnings = evaluate_nutrition(
            calories=row["calories"],
            protein_g=row["protein_g"],
            carbs_g=row["carbs_g"],
            fat_g=row["fat_g"],
            fiber_g=row["fiber_g"],
            sugar_g=row["sugar_g"],
            sodium_mg=row["sodium_mg"],
        )
        session.add(
            Dish(
                name=row["name"],
                meal_type=row["meal_type"],
                ingredients=row["ingredients"],
                cost_per_serving=row["cost_per_serving"],
                calories=row["calories"],
                protein_g=row["protein_g"],
                carbs_g=row["carbs_g"],
                fat_g=row["fat_g"],
                fiber_g=row["fiber_g"],
                sugar_g=row["sugar_g"],
                sodium_mg=row["sodium_mg"],
                benefits=auto_benefits,
                warnings=auto_warnings,
                is_healthy=is_healthy,
                is_active=True,
            )
        )
        existing_names.add(row["name"])
        inserted += 1

    if inserted:
        session.commit()

    return inserted
